Update tfsec.yml

diff --git a/.github/workflows/tfsec.yml b/.github/workflows/tfsec.yml
--- a/.github/workflows/tfsec.yml
+++ b/.github/workflows/tfsec.yml
@@ -1,10 +1,9 @@
-name: tfsec
+name: Terraform Code Scan
 
 on:
-  issues:
-    type:
-     -opened
-     -closed
+  push:
+    branches:
+      - main
 
 jobs:
   terraform_scan:
@@ -20,15 +19,12 @@ jobs:
         chmod +x tfsec
         sudo mv tfsec /usr/local/bin/
 
-    - name: Run tfsec scan and save results
+    - name: Run tfsec scan
       run: |
-        tfsec . --format json > tfsec_results.json
-        tfsec . --format junit > tfsec_results.xml
-
-    - name: Upload results
-      uses: actions/upload-artifact@v2
-      with:
-        name: tfsec-results
-        path: |
-          tfsec_results.json
-          tfsec_results.xml
+        tfsec .
+        TFSEC_EXIT_CODE=$?
+        if [ $TFSEC_EXIT_CODE -eq 0 ]; then
+          echo "Terraform code scan passed successfully."
+        else
+          echo "Terraform code scan failed with issues."
+        fi
